export default {
    VALIDATION_ERROR : 'VALIDATION_ERROR',
    BASE_ERROR : 'BASE_ERROR',
    STARWARS_CUSTOM_ERROR : 'STARWARS_CUSTOM_ERROR',
    POSTGRESSQL_CONNECTION_ERROR : "POSTGRESSQL_CONNECTION_ERROR",
    POSTGRESSQL_CLOSE_CONNECTION_ERROR : "POSTGRESSQL_CLOSE_CONNECTION_ERROR"
}