apiVersion: v1
kind: Namespace
metadata:
  name: demo-space
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-space
  name: graphql-app-deployment
  labels:
    app: cache-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-demo
  template:
    metadata:
      labels:
        app: cache-demo
        track: stable
    spec:
      containers:
        - name: graphql-container
          image: demoexample1:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-space
  name: graphql-demo-svc
  labels:
    app: cache-demo
spec:
  ports:
    - port: 8080
      targetPort: 3001
      nodePort: 30080
  selector:
    app: cache-demo
  type: NodePort
