apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: demo-space
  name: graphql-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-demo
  template:
    metadata:
      labels:
        app: graphql-demo
        track: stable
    spec:
      containers:
        - name: graphql-container
          image: local-graphql-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-space
  name: graphql-demo-svc
  labels:
    app: graphql-demo-svc
spec:
  ports:
    - port: 8080
      targetPort: 3000
      nodePort: 30080
  selector:
    app: graphql-demo-api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: demo-space
  name: graph-demo-svc-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: graphql-demo-svc
              servicePort: 8080
            path: /myDemo
